### ISSUE TITLE
Ability to destroy List object

### ISSUE THREAD

**Issue by sawyerh** [javve/list.js#121]
I'm working on a page where there are multiple lists, but only one is visible at a time. When the lists are toggled, I'd like to destroy the previous List instance and create a new one for the newly visible list. 

Basically, this is what I'd like to do:

```
// Restore previous list items to default state, and remove List functionality
oldList.removeClass('list')
listObj.destroy();

// Shows the new list and adds the List functionality to it
newList.addClass('list');
listObj = new List('files', listOptions);
```

I'm not seeing this method anywhere, is this something that would need added or am I looking over something in the code?

To give some context, this is what the page looks like (http://d.pr/i/iH0y).

**Comment by nicoruti** [comment]
Sorry for reviving this old post, but I struggled with the same issue and found a workaround, probably helpful for next (desperate) readers.
Similar as the TS posted, I'm creating a new search instances and would like to clean up the old one. Otherwise it interferes with the new search instance and overwrites results of the new one. The trick is to remove the listeners on the search field of the old instance. Easiest to do so is

```
var searchField = document.getElementById("searchinput"),
        searchFieldClone = searchField.cloneNode(true);
searchField.parentNode.replaceChild(searchFieldClone, searchField);
```

When cloning elements, the listeners are not discarded (details see <a href="http://stackoverflow.com/questions/19469881/javascript-remove-all-event-listeners-of-specific-type">here</a>.
