### ISSUE TITLE
Table is Being Limited to 200

### ISSUE THREAD

**Issue by matyre73** [javve/list.js#236]
For some reason when I add the list class on to the tbody the rows are limited to 200.

**Comment by simonseddon** [comment]
Sorry, I know this is closed but I'm having issues with the page parameter. On the one hand it's documented that it dictates paging, when using the the pagination plugin. On the other hand, as documented above, it overrides a built-in limit (200) for the total records?

What if you have have 200+ records and want a little control over pagination?

Note, rather than the method above, I had to set indexAsync to false to get all of my records to show when I ran in to a similar issue of records disappearing. I was under the impression that this option was better set to true for many records?

I'm concerned about this issue, as I currently have 174 records displaying with pagination set to 20 per-page, as defined by the page option. My records will shortly go above 200.. at this point I'm afraid that the current set up will cause records to disappear.
