### ISSUE TITLE
Filter with data attributes

### ISSUE THREAD

**Issue by nil** [javve/list.js#399]
I was wondering if you can use the Filter feature without showing the value but using data attributes.

I have three groups called `group-1`, `group-2` and `group-3`. I don't want to show the name of the group to the user but I still want to filter by group.

**Comment by ursbraem** [comment]
Doesn't the example on http://www.listjs.com/examples/data-attributes-custom-attributes do that? If you type in the timestamp 12345, you'll get Jony Stromberg.

Then you should be able to trigger the data attributes from selects or checkboxes as in http://codepen.io/JasonEspin/pen/zGvjwR or http://codepen.io/waynehoover/pen/KBqhF

Which is what I'm also about to try. 

I'm missing an "official", best practice example for such filters though.

**Comment by nil** [comment]
Oh! I didn't see it! Thanks for your comment.

**Comment by Log1x** [comment]
This issue is quite old, but in case anyone stumbles upon it– I found the lack of examples for a simple filter rather frustrating.

https://codepen.io/Log1x/pen/LajRyo

Here is a straight-forward Codepen on filtering a list of items by category/group using purely data-attributes with no hard-coded `valueNames`.
