### ISSUE TITLE
index async with very large dataset

### ISSUE THREAD

**Issue by sudipster** [javve/list.js#426]
Hi, I have a list with about 10,000 items. If I don't use idexAsync = true, the list freezes. However, I have a situation where I have to fire an event right after the list is loaded (basically right after indexing operation is complete).  Is there an event in list, which lets me know when indexing operation is complete? Thanks.

**Comment by sudipster** [comment]
updated event?

**Comment by sudipster** [comment]
I tried using updated event. But since I call list.filter() in the callback attached to the updated event which further calls update method.. This is causing a recursion: "Uncaught RangeError: Maximum call stack size exceeded".

**Comment by sudipster** [comment]
Solved this using jquery callbacks.

**Comment by johnvicencio** [comment]
Hello! I have the same question. But I couldn't figure out how to use this indexAsync option using Example 3: Create list on initialization: Version 2. Do you do something like and if so is there anything else I should be doing? I only have less than 2,000 records it seems to be blank. 

var options = {
    item: 'hacker-item',
     indexAsync: true
};

// let say 2K records here instead of two
var values = [
    { name: 'Jonny', city:'Stockholm' }
    , { name: 'Jonas', city:'Berlin' }
];

var hackerList = new List('hacker-list', options, values);
