### ISSUE TITLE
Multiple Search

### ISSUE THREAD

**Issue by grahn195** [javve/list.js#439]
How can i make a Multiple Search in colums?

http://codepen.io/grahn195/pen/PzXZor

dont work...

hackerList.search(name, ['name']).hackerList.search(energieart, ['energieart']);
hackerList.search(name, ['name'],energieart, ['energieart']);
hackerList.search(name, { name: true,},energieart, { energieart: true,});

**Comment by carlafranca** [comment]
This way you wont need the bt. It will only search based on the input field
http://codepen.io/carlafranca/pen/oLRzJE

You could have a single input field and a dropdown list or bts to change the columns in 
hackerList.search(searchString, columns)

**Comment by j4kim** [comment]
thanks @carlafranca 
I updated your pen, which doesn't work anymore since the list.js include is dead.
https://codepen.io/anon/pen/WdmRwj

**Comment by j4kim** [comment]
I've updated it to handle AND operator between the search arguments: https://codepen.io/anon/pen/YYgxKp

**Comment by mbkupfer** [comment]
Sorry if this is resurrecting a close issue, but I though it would be relevant place to ask. 

Is there a way to implement the multi search in the codepen above, but also add in the ability to split inputs by spaces? I know that I can do the Array.split(" ") function, but I'm a bit fresh on the js to understand how to piece it into that filter function.

**Comment by j4kim** [comment]
If I understood correctly, here it is : https://codepen.io/j4kim/pen/dmxVME
The `some` method implements the OR operator on an array. If one of the terms, separated by spaces, is included in the item value, the item is not filtered.

**Comment by mbkupfer** [comment]
@j4kim, thanks that works! 

Just as a quick side note, arrow functions and includes() are not compatible with IE. Here is the IE compliant version I created in case anyone needs it. 

```
$(".filter").keyup(function () {
  hackerList.filter(function (item) {
    return options.valueNames.every(function (name) {
      var searchTerms = $("#" + name).val().toLowerCase().split(" ");
      var itemValue = item.values()[name].toLowerCase();
      return searchTerms.some(function (term) {
        return (itemValue.indexOf(term) >= 0);
      });
    });
  });
});

```

**Comment by scannermobs** [comment]
Apologies for resurrecting this thread. But I'm trying to implement 'multiple search' similar to the OP. I need to use search, rather than filter, due to peculiarities in data.

I cannot figure out how to 'chain' multiple search parameters, it seems that the last one always supersedes any that come before it.

Basically I have 3 inputs, all to perform searches across the same items but searching within their own data source.

If someone could please confirm whether what I'm trying to do is even possible with the search function, that would be great. If it is, any brief examples on the syntax for combining the searches would also be much appreciated.

Thanks

**Comment by javve** [comment]
This is kind of a power feature, but I'm thinking about a solution for multiple search and filters at the same time. However I think it would be a pretty big update and there by part of List.js 2.0 or something. I'm currently collecting all search related issues here: #635 and will there by close this one for now.
