### ISSUE TITLE
FR: Add Span and Class to HighLight Result

### ISSUE THREAD

**Issue by X-Raym** [javve/list.js#446]
Hi,

It may be cool if the List.js was able to add span and class to text inside the list item that match the filter/search criteria.

E.g, i fyou have this list =>
```html
<ul>
  <li>UnusedItem</li>
  <li>GetMediaItemTrack</li>
  <li>GetTrackMediaItem</li>
<ul>
```
Then filter for "Track" will output as =>
```html
<ul>
  <li>UnusedItem</li>
  <li>GetMediaItem<span class="list-js-match">Track</span></li>
  <li>Get<span class="list-js-match">Track</span>MediaItem</li>
<ul>
```

This way, we could add a but of style to highlight or underline part of the text that was involved in the result.
![Exemple of styling](https://monosnap.com/file/gG1OKhxdYvLiBTv8lcp4WFBplqpMdP.png)

Also, a  `list-js-match-fuzzy` could be considered for part of the text involved in a fuzzy result.

Thanks for your great script,

Cheers!

**Comment by X-Raym** [comment]
Thanks to [bartaz jquery.highlight.js ](http://bartaz.github.io/sandbox.js/jquery.highlight.html)script... Solved :)

[Demo](http://codepen.io/X-Raym/pen/YGjmYJ?editors=1010).

**Comment by chsteiner** [comment]
This solution does not work anymore it seems. Not only because of the broken rawgithub link of jquery.highlight. I tried to make it work locally but I can't figure out how to keep everything visible after a search and instead only highlight the results. THis would be an especially interesting feature for fuzzy searches!
