### ISSUE TITLE
Multiple value same class

### ISSUE THREAD

**Issue by mjniuz** [javve/list.js#449]
I want to get search by class **s_num** inside of element class **main-search**, but it just work only first row of table class s_num, when i search with keywords for second row or more, it not work/showing...

this is my code

```
<tbody id="search">
<tr class="main-search">
  <td>Component 1
<tbody style="display:none" id="tbody-a">
<tr> 
<td class="s_num">11212</td> 
</tr>
<tr>
<td class="s_num" >1121</td>
</tr>
</tbody>
  </td>
</tr>

<tr class="main-search">
  <td>Component 2
<tbody style="display:none" id="tbody-b">
<tr> 
<td class="s_num">2212</td> 
</tr>
<tr>
<td class="s_num" >2231</td>
</tr>
</tbody>
</td>
</tr>

</tbody>
```

JS
```
var options = {
            valueNames: [ 's_num' ]
        };
var searchMe = new List('search', options);
```

**Comment by javve** [comment]
This isn't possible due to List.js's architecture. I'm thinking about supporting arrays with values (which this case would be) but I'm not sure that a critical number of List.js users need it :/

**Comment by robsch** [comment]
@javve: I'm one that needs that!

I'm not sure if I got that right, since the example contains a table. 

My Situation with which I have a problem: Show a list where each entry has zero, one or more tags (labels). I'd like to filter for those tags. Currently, list.js can only filter for the first tag.

I think I have to workaround now that with some kind of hidden element for each entry, containing the tags concatenated into one string and set the search to it.
