### ISSUE TITLE
How to hide pagination if pages <= 1?

### ISSUE THREAD

**Issue by lavezzi1** [javve/list.js#466]
Hello, 

I want to hide pagination if only one page. Whats the best way to do it?

I tried:

```
        var paging = document.getElementById('paging');

        if (pages.length <= 1) {
            paging.style.display = 'none';
        }
```

Doesn't works.

**Comment by javve** [comment]
Yeah do like @HyeinKang, and add that thing to `listObj.on('updated', function() { /* code *});`

**Comment by elixirgraphics** [comment]
While doing what @HyeinKang recommends seems to work, it also is returning an error of `$ is not a function. (In '$('.pagination')', '$' is undefined`

Wondering what I might be doing wrong here.

![screen shot 2017-03-16 at 11 01 21 am](https://cloud.githubusercontent.com/assets/2013801/24002756/f39a3d00-0a37-11e7-8487-f0b2c97c466f.png)

**Comment by schleimschein** [comment]
@elixirgraphics `$` is a valid variable name in JS, but usually it is used as a shortcut for jQuery. Since it seems as the solution by @HyeinKang uses jQuery selectors, make sure to include the jQuery lib in your document. 

Otherwise, if you want to use only plain JS,  you can also use exchange 
`$('pagination')`  
by 
`document.getElementsByClassName("pagination")[0]`
(supposed you only have one element with the class "pagination", otherwise you would have to loop over the array that document.getElementsByClassName("pagination") returns) and 
`.css('display', '<the_corresponding_attribute>') `
by 
`.style.display = 'none';` .
