### ISSUE TITLE
Uncaught TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by aap-ryan** [javve/list.js#480]
No matter if I install using NPM or try loading via CDN, I get the same error. Checking the uncompressed version, it looks like the issue falls in trying to call set on templater, which is set using an external src file that is not present. Even when I try to bring those files in from the src directory on this repo I still get the same error. Error occurs when trying to add to an existing list.

**Comment by satrioaw** [comment]
23.58, 10 Januari 2017, Ryan Davis <notifications@github.com>:No matter if I install using NPM or try loading via CDN, I get the same error. Checking the uncompressed version, it looks like the issue falls in trying to call set on templater, which is set using an external src file that is not present. Even when I try to bring those files in from the src directory oln this repo I still get the same error. Error occurs when trying to add to an existing list.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Sent from Yandex.Mail for mobile

**Comment by satrioaw** [comment]
23.58, 10 Januari 2017, Ryan Davis <notifications@github.com>:No matter if I install using NPM or try loading via CDN, I get the same error. Checking the uncompressed version, it looks likel the issue falls in trying to call set on templater, which is set using an external src file that is not present. Even when I try to bring those files in from the src directory on this repo I still get the same error. Error occurs when trying to add to an existing list.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Sent from Yandex.Mail for mobile

**Comment by cleversonc6** [comment]
I'm also having the same problem

**Comment by rajatrawataku1** [comment]
Any solution for this guys ???

**Comment by RuiLoureiro** [comment]
I'm also having this problem. Any fix yet?

**Comment by javve** [comment]
Hmm, I need to see some code to figure out why you get this error.

**Comment by vladar** [comment]
In my case it happened when list `id` attribute in HTML didn't match list id in js.

**Comment by mica-sirup** [comment]
I hade the same issue. I solve it by using the demos html tags so
```
<div id="TheWrapperID">
  <!-- class list seems to be important -->
  <ul class="list"></ul>
</div>
```
Then
let projectsList = new List('TheWrapperID', options);
