### ISSUE TITLE
Unable to Find & (ampersand character) correctly

### ISSUE THREAD

**Issue by jochristianto** [javve/list.js#490]
My data include names like "A & B", "B & C", "D&E", etc.

If you try to find "A &" or "D&", it is still working.

But once you try "A & B", it will fail. It will only success if you search it as "A &amp; B".

**Comment by Stolzenhain** [comment]
this relates to #147

Ampersands belong to special HTML chars[^1], so the item value does not contain `&` but `&amp;` as a string value. This might be the reason why `A &` produces results, whereas `& B` doesn't.

On my side, this doesn't happen on searches, so there might be further conversions.

Various happen to the strings due to how the values are parsed, see #19 which leads to ampersands being found by searching for `amp`.

Also note: JS returning things like the `value` attribute with converted ampersands – whereas the value string in a list.js item keeps the escaped char, making it impossible to compare.

[^1]: see: [Named character references](https://html.spec.whatwg.org/multipage/named-characters.html)
