### ISSUE TITLE
Sort order indicator.

### ISSUE THREAD

**Issue by hifall** [javve/list.js#531]
How do I add an icon with 2 states asc/desc to indicate current sort order? Is this built in with list.js, or do I have to do it manually?

**Comment by thenatsky** [comment]
You do it with css.

the html:
link in fontawesome if you havent already - I do this because I prefer glyph icons instead of images:
`	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
`
then in the table header, define like this:
`<th class="sort sort-control" data-target="list" data-sort="field_name" role="button">Field Name</th>`

btw, make sure you include the class "sortable" in the `<table>` tag

the css: 
```
table.sortable .sort:before {
	font-family: FontAwesome;
	font-size: 0.75em;
	color: #333;
	font-weight: lighter;
	content: "\f0dc";
	padding-right: 0.7em;
}

table.sortable .sort.asc:before {
	content: "\f0de";
}

table.sortable .sort.desc:before {
	content: "\f0dd";
}

```
ps - this has 3 states: the loaded default, asc and desc.

**Comment by hifall** [comment]
Thanks for your answer, @thenatsky!

**Comment by anselal** [comment]
@javve Why don't we add this be default in listjs ?
We can use unicode symbols (https://www.w3schools.com/charsets/ref_utf_arrows.asp) without the need to import FontAwesome of LineAwesome or whatever..
