### ISSUE TITLE
IE Back Button - Remember Results?

### ISSUE THREAD

**Issue by hitolonen** [javve/list.js#544]
We are using [checkboxes](https://codepen.io/JasonEspin/pen/bdajKo) with the filtering and FF, Chrome and Safari remember the checkbox and the filtered content when going from the filtered results page to new page to back to the filtered results page by using the browser back button. IE doesn't remember the results.

Workflow:

1. on page 1 clicking checkbox and results go from showing all to matching the filter checkbox.
2. from page 1 go to another page, eg page 2
3. on page 2 click the back button
4. back on page 1 the previously checked checkbox is checked and ff, chrome and safari remember the matched filtered content. IE shows all results but keeps the checkbox checked.

Is this script related or IE related?

For now we are forcing page reload on IE so that it removes the checked checkbox.

**Comment by javve** [comment]
List.js does nothing to help the browser remember which filters are active or anything else when it comes to using the back button in the browser etc. 

So I would say that this has something to do with how the browsers are built. 

...I'll close this issue since List.js is not built to support the History API and any behaviour is just random or unintentional :)

**Comment by Julianoe** [comment]
I would add a link to this more recent issue on how to control it a bit better
https://github.com/javve/list.js/issues/650
