### ISSUE TITLE
Feature Request: List search results in order of relevance

### ISSUE THREAD

**Issue by jeffreymeng** [javve/list.js#628]
It would be nice to be able to have an option to display the list in order of relevance after searching, instead of just ascending/descending order.

This was mentioned in #57, the origianal issue for fizzy-search.

**Comment by javve** [comment]
I thinks this could be a pretty cool feature. However probably pretty hard to implement. Maybe there is a (really small) open source lib that could help somewhere? It can't be too much code because then I don't want to add it to the core lib.

I'll close this issue for now but keep a reference to it here: #635
