### ISSUE TITLE
List search doesn't work on iOS devices (iPad, iPhone)

### ISSUE THREAD

**Issue by ecandino** [javve/list.js#66]
Filtering via search works on the desktop browser, but not mobile safari. There are no console errors on the device when the list function is called, it just doesn't filter. Any thoughts?

**Comment by davemh** [comment]
@ecandino I'm also running into this issue with a table on Safari for iOS, though the examples on the site work fine on iOS. I'm curious if you were able to figure out the problem.

**Comment by madebyelmcity** [comment]
Chiming in, too. I'm also encountering the issue. No search results show on iOS devices. Works fine in the simulator, and on desktop browsers. @davemh @ecandino

**Comment by davemh** [comment]
@madebyelmcity I was able to get search to work on iOS devices by making sure the table was narrow enough to fit within in the viewport on smaller screens, i.e. using relative widths in my CSS rather than px widths to make sure the table was responsive. Initially I specified widths in px's and when it was wider than the viewport, list.js didn't work. I'm not sure *why* this fixed the problem, but it did.
