### ISSUE TITLE
Previous/Next for paging

### ISSUE THREAD

**Issue by ajrdesign** [javve/list.js#82]
Is it a possibility to get next/previous page buttons added into the Paging plugin?

**Comment by ksciana** [comment]
Any progress?

**Comment by bstaruk** [comment]
This missing feature is the reason for me deciding against using this library, which is a shame because it seemed to handle everything else perfectly.

**Comment by Salvatos** [comment]
I can't remember where I grabbed the code and I probably didn't come up with it myself, but I actually implemented this on a website 6 months ago. Since I've never really used version control, I'll post the changes I made here so hopefully someone can consider adding them to the main branch. Note I am using an older version from before the pagination plugin was merged in, but the code seems to be mostly the same.

FIND:
```
           right = options.right || options.outerWindow || 0;
```
REPLACE WITH:
```
            right = options.right || options.outerWindow || 0,
            includeDirectionLinks = options.includeDirectionLinks || false,
            leftDirectionText = options.leftDirectionText || '&laquo;',
            rightDirectionText = options.rightDirectionText || '&raquo;';
```
FIND:
```
        pagingList.clear();
```
REPLACE WITH:
```
        pagingList.clear();
        if (includeDirectionLinks) {
          // Include previous link
          item = pagingList.add({
              page: leftDirectionText,
              dotted: false
          })[0];
          classes(item.elm).add("prev");
          if (currentPage - 1 > 0) {
            addEvent(item.elm, currentPage - 1, page);
          } else {
            classes(item.elm).add("disabled");
          }
        }
```
FIND:
```
                classes(item.elm).add("disabled");
            }
        }
    };
```
REPLACE WITH:
```
                classes(item.elm).add("disabled");
            }
        }
        if (includeDirectionLinks) {
          // Include next link
          item = pagingList.add({
              page: rightDirectionText,
              dotted: false
          })[0];
          classes(item.elm).add("next");
          if (currentPage + 1 <= pages) {
            addEvent(item.elm, currentPage + 1, page);
          } else {
            classes(item.elm).add("disabled");
          }
        }
    };
```

And of course you need to set `includeDirectionLinks: true` in your options. You can also set leftDirectionText and rightDirectionText to not use the defaults (« and »).

Hope that helps!

**Comment by hifall** [comment]
Any progress?

**Comment by vikramksrm** [comment]
Any progress?

**Comment by jmatthewyoung** [comment]
Dude @Salvatos I hope there is a golden throne for you in heaven cause this comment just saved my ass man you are the fucking bomb.
