### ISSUE TITLE
Duplicate items when adding array of items

### ISSUE THREAD

**Issue by Gori** [javve/list.js#93]
I'm getting duplicate items if I add a whole array with the .add(array) method, but no duplicates if I loop through the same array and add each item with .add(object) instead.

**Comment by jackeastburn** [comment]
I'm having the same problem unfortunately. It's being done within an AJAX call which seems to give list.js a bit of trouble. Like Gori I'm logging the array before I send it in and it's the right length, but it comes out doubled. Like Gori said, the order it comes out seems random as well.

Unfortunately, I need to procedurally generate a number of elements of my table that are in each searchable row, but not searchable themselves and therefore not on the list. Unfortunately, until this is fixed I can't use the plugin, which is too bad because it's so cool!
